version: '3.4'

services:
  bwf.api.host:
    image: bwfapi:dev
    container_name: BWF.Api.Host
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "BWF.Api.Host"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_bwf.api.host$
    volumes:
      - /Users/dmitrii.maskevich@futurice.com/Projects/bad-words-finder/src/BWF.Api.Host:/app
      - /Users/dmitrii.maskevich@futurice.com/Projects/bad-words-finder/src:/src
      - /Users/dmitrii.maskevich@futurice.com/vsdbg/vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_bwf.api.host$

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_bwf.api.host$ \"/src/../../../../dmitrii.maskevich%40futurice.com/Projects/bad-words-finder/src/BWF.Api.Host/bin/Debug/netcoreapp3.1/BWF.Api.Host.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true